# Generated by Django 4.2.4 on 2023-08-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('title_text', models.TextField()),
                ('title_len', models.IntegerField()),
                ('meta_text', models.TextField()),
                ('meta_len', models.IntegerField()),
                ('h1_text', models.TextField()),
                ('h1_len', models.IntegerField()),
            ],
        ),
    ]
